#!/bin/bash

declare -a folders=("italian" "norwegian" "polish" "romanian" "serbian" "spanish" "swedish")

for folder in "${folders[@]}"
do
	bzcat wiki_data/$folder/*.bz2 | ./WikiExtractor.py -cb 250K -o wiki_output/$folder -
done
